### ISSUE TITLE
Clarify timing of exceptions from curried functions

### ISSUE THREAD

**Issue by rossberg-chromium** [SMLFamily/BasisLibrary#10]
Some curried functions in the Basis can raise exceptions. In a few cases it is underspecified when these are raised. For example, does `Time.fmt ~1` throw, or is the exception deferred until the second argument is provided?

Affected functions:

- Real.fmt
- Time.fmt
- others?

**Comment by JohnReppy** [comment]
I agree that the Basis Library should specify this behavior.  In fact, it appears that there is some disagreement among implementations currently.  I tried `Time.fmt` and found that **SML/NJ** defers the exception until all arguments are present; **MLton** generates it on the partial application; and **Moscow ML** does not generate the exception at all.  I haven't checked any of the other implementations.

Once we have a decision for what the behavior should be, we should create a proposal to clarify the behavior (similar to 2015-001).

**Comment by JohnReppy** [comment]
Looking more closely at the Basis Library specification, it states for `Real.fmt` that

> The exception should be raised when `fmt spec` is evaluated.

Therefore, I think that `Time.fmt ~1` should raise `Size`.  I'll create a proposal to this effect (and a bug report for **SML/NJ**).
