### ISSUE TITLE
Discussion for proposal 2016-003 (Conformance levels)

### ISSUE THREAD

**Issue by ratmice** [SMLFamily/BasisLibrary#20]
Discussion of proposal [2016-003 (Conformance levels)](https://github.com/SMLFamily/BasisLibrary/wiki/2016-003-Relaxed-conformance-for-less-traditional-kernels)

[Edit: This proposal only delves into the subset of the basis which is currently Required, and the portability to non-traditional kernels.]

**Comment by JohnReppy** [comment]
Unclear to me what the proposal is proposing.  Perhaps it should be rewritten to state that a specific list of modules is optional in a *minimal implementation* of the Basis Library.

**Comment by ratmice** [comment]
Thanks John, I have tried to clarify it (removing a large section, which i think distracted from the main point, summarizing that in a paragraph in the synopsis), and moving more to as you suggest.

**Comment by ratmice** [comment]
FWIW, I'm going to just close this, It seems what i'm after is already attainable (and less ad-hoc) from Matthias Blume's "Portable Library descriptions for Standard ML", that more compilers don't implement this interface is probably not a good reason for including such a library description of the basis library as a meta-data structure within the basis library itself.  Either way that proposal is probably a better starting point.
